### PR TITLE
workaround to get the same path as on vivid to the database

### PR DESCRIPTION
**Pull request by StefWe**
#87 is the reported problem.

We need to talk about whether we can accept the change. All those who already have an album under xenial won't see it anymore.

### CODE REVIEW

**Comment by TronFortyTwo** [comment]
Maybe we may read albums from both the xenial and vivid database (if available)?

**Comment by StefWe** [comment]
And in which database we should write?
If the problem had arisen before OTA5, the solution would have been simpler.

**Comment by bhdouglass** [comment]
Would it make more sense to write something to migrate the vivid data to xenial? We should probably avoid breaking the existing database and upsetting people.

**Comment by StefWe** [comment]
I think we have to fix the path for the database to the original one `/home/phablet/.local/share/com.ubuntu.gallery/database/gallery.sqlite`

Maybe we can add some code which will check if the database is in the "right" place. If not it will move the database.
gallery-appstart

**Comment by TronFortyTwo** [comment]
This is closed, but we'll continue to work on this after to move to gitlab ;-)

**Pull request closed without merging**
