### PR TITLE
Update framework and policy version to 16.04 + change maintainer

### PR DESCRIPTION
**Pull request by UniversalSuperBox**
This changes all of the following:

* Updates apparmor policy
* Updates SDK version
* Updates version number above what's already in the OpenStore (so both the store and the Settings updater will grab it)
* Updates maintainer to UBports

### CODE REVIEW

**Comment by StefWe** [comment]
So it there will be only one master branch? Is it planed to release new versions to 15.04?

**Comment by Flohack74** [comment]
No we wont release new versions to 15.04 anymore. The idea is that OTAs are being installed by everyone over time, and as a little incentive also App updates should only target the current release (its the one that is inside the current OTA). As we are on LTS this will happen only every x years...

**Comment by StefWe** [comment]
thank you for your explanation @Flohack74

**Comment by StefWe** [comment]
The branch has been merged, can it be deleted?

**Pull request merged**
