### PR TITLE
fixed two missing strings in the pot file

### PR DESCRIPTION
**Pull request by StefWe**

### CODE REVIEW

**Comment by StefWe** [comment]
Sorry i made a extra pr for the pot file
should i close this and add the pot file here?

**Comment by StefWe** [comment]
Done, sorry for the confusion with two pr's

**Comment by StefWe** [comment]
do weblate pick up a new .pot file automatically?

**Comment by Flohack74** [comment]
Yes it will pick it up automatically thats the reason why we have it ;)

**Comment by StefWe** [comment]
When is the new .pot file loaded in the weblate and can be translated?

**Pull request merged**
