### PR TITLE
Translation issues fixed

### PR DESCRIPTION
**Pull request by StefWe**

### CODE REVIEW

**Comment by StefWe** [comment]
The .po files are not updated to the new structure of the .pot file. Is there anything we need to change in the weblate or how can this changes take effect?

**Comment by Flohack74** [comment]
Weblate made again merge conflicts, and I have to fix everything manually. I dont understand how this workflow will ever work automatically....

**Comment by Flohack74** [comment]
No should be good now. Please check tomorrow´s 16.04 devel update. Another story is that we need to publish it to the Openstore but due to vivid and xenial needing different builds probbaly which Openstore does not support yet this is on hold.

**Comment by StefWe** [comment]
The changes are really small. So do you mean we should publish a new version?

**Comment by StefWe** [comment]
i checked it and its fixed and work well on the build r369

**Comment by Flohack74** [comment]
Thanks. New version publish however will be interesting, we still do not have an automatic way to provide files for vivid, xenial as click for the Openstore ;)

**Comment by StefWe** [comment]
If we create a new verion for 15.04 we can bring this in open-store
For 16.04 everyone get a new version over the nighly build and update. If 16.04 is stable then we need to find a solution for the openstore.
What do you think?

**Comment by StefWe** [comment]
Ok, i understand the basic problem.the
I never published anything at the openstore. I need to try how this works at the moment.

**Pull request merged**
