### PR TITLE
Preview animated gifs

### PR DESCRIPTION
**Pull request by nfsprodriver**
If someone wants to try, still buggy yet.
#41

### CODE REVIEW

**Comment by nfsprodriver** [comment]
Well, that's a fanvy try which we may do in a completely different way because it costs losts of performance. So by me it's not a WIP, but others can trst and contribute in that part ;)

**Comment by Flohack74** [comment]
Well you wrote its buggy and laggy, so its more or less WIP or invalid. Definitely not eligible for merge then.

**Comment by TronFortyTwo** [comment]
We're closing all PRs to move the repository to Gitlab. Since this PR looks like is not going to be merged, I'll close it for now.

**Comment by StefWe** [comment]
Is there a date when this archive will be moved?

**Pull request closed without merging**
