### PR TITLE
Using Suru theme icons, instead of gallery-app own icons

### PR DESCRIPTION
**Pull request by TronFourtyTwo**
Basically there were many icons present in the Suru Icon theme that has been designed again by previous devs. Is always better to use Ubuntu Components Icon instead, I saved some kilobyte of space and the app is more integrated with ubuntu touch graphic style.
I also bumped the version number.

### CODE REVIEW

**Comment by TronFourtyTwo** [comment]
[com.ubuntu.gallery_2.9.4_armhf.click.zip](https://github.com/ubports/gallery-app/files/1105724/com.ubuntu.gallery_2.9.4_armhf.click.zip)

Here is a click package to test changes on the fly.

**Comment by Flohack74** [comment]
Shall I wait or is it ready? =)

**Comment by TronFourtyTwo** [comment]
Ready, ready. ;)

**Comment by Flohack74** [comment]
I installed your click from yesterday, but I dont see much difference :) - ah and is there a way to cancel edit mode?

**Pull request merged**
